version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: iot_db
    restart: always
    environment:
      POSTGRES_USER: dazhlo
      POSTGRES_PASSWORD: dazhlo45588
      POSTGRES_DB: iot_db_dev
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: